Use live_server_url as IDTRACKER_BASE_URL in IetfLiveServerTestCase
painless-security/ietfdb pull request #49
Opened 2021-08-31 17:43 UTC by jennifer-richards

Addresses [ticket 3203](https://trac.ietf.org/trac/ietfdb/ticket/3203).

The problem encountered in the ticket resulted from JS making xhr requests to relative URLs computed by `Document.get_href()`. I don't understand exactly how that is ending up relative to the `IDTRACKER_BASE_URL`, but it seems like the correct behavior.

An alternative approach is to override the `MEETING_DOC_*REF` settings to be absolute URLs. That is more tailored to the problem here, but I can't think of any reason why we would want to be pointing to the `IDTRACKER_BASE_URL` from `settings.py` or `settings_local.py` while using the live server. This more general replacement is more likely to prevent future request leakage.

2021-09-06 23:13 UTC, meadmaker requested changes

2021-09-06 23:14 UTC, meadmaker commented
This is less a request for change and more a request for an explanation of what the heck is going on here?

2021-09-07 11:59 UTC, jennifer-richards commented on ietf/meeting/tests_js.py
> +from django.conf import settings
This is the official way to import Django's settings (see the last paragraph of [this section of the Django settings docs](https://docs.djangoproject.com/en/2.2/topics/settings/#using-settings-in-python-code)). It deals with things like finding the correct settings module based on the environment settings. I haven't tested this, but I expect it means that settings in the `settings_testsqlite.py` file used for testing were not actually seen in this module.

In this particular case, I needed to make the change in order for the `@override_settings()` decorator to work.

I've reported this as a general issue in the code here: https://trac.ietf.org/trac/ietfdb/ticket/3392

2021-09-07 15:24 UTC, meadmaker approved these changes

2021-09-07 18:19 UTC, merged